on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

name: Deploy

jobs:
  deploy-digests:
    name: Deploy digests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Generate configuration
        run: python ./generate.py

      - name: Generate HTML
        run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" python -m dinghy ./config.yml
          mkdir ./digests/ && mv *.html ./digests/

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./digests
